name: Ubuntu

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Build Module 
      run : sh PythonWrapper/build.sh
      
    - name : Run tests 
      run : python3 -m unittest -v