name: Ubuntu

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2

    - name : Build module 
      run : |
            cd PythonWrapper \
            sh build.sh
    
    - name : Install dependencies
      run : pip install numpy
      
    - name : Run tests 
      run : python3 -m unittest -v